In [1]:
import numpy as np
import pandas as pd

<h1>Apply Functions</h1>

In [2]:
df = pd.DataFrame(data=np.arange(12).reshape(3,4),columns=list("ABCD"))

In [3]:
df

   A  B   C   D
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [4]:
df.apply(np.sqrt)

          A         B         C         D
0  0.000000  1.000000  1.414214  1.732051
1  2.000000  2.236068  2.449490  2.645751
2  2.828427  3.000000  3.162278  3.316625

In [5]:
df.apply(np.cumsum)

    A   B   C   D
0   0   1   2   3
1   4   6   8  10
2  12  15  18  21

In [6]:
df.apply(np.cumsum,axis=1)

   A   B   C   D
0  0   1   3   6
1  4   9  15  22
2  8  17  27  38

In [7]:
df.apply(lambda i: i+2)

    A   B   C   D
0   2   3   4   5
1   6   7   8   9
2  10  11  12  13

In [8]:
df.apply(lambda i: i+2,axis=0)

    A   B   C   D
0   2   3   4   5
1   6   7   8   9
2  10  11  12  13

In [9]:
df.apply(lambda i:i%2==0)

      A      B     C      D
0  True  False  True  False
1  True  False  True  False
2  True  False  True  False

In [10]:
def test(x):
    return list(filter(lambda i:i%2==0,x))

In [11]:
df.apply(test)

A     [0, 4, 8]
B            []
C    [2, 6, 10]
D            []
dtype: object

In [12]:
def get_mean(x):
    return np.mean(x)

In [13]:
df.apply(get_mean)

A    4.0
B    5.0
C    6.0
D    7.0
dtype: float64

In [14]:
df.apply(np.mean)

A    4.0
B    5.0
C    6.0
D    7.0
dtype: float64

<h1>Histogramming</h1>

In [15]:
df = pd.DataFrame(data=np.random.randint(0,10,size=100).reshape(20,5),columns=list("ABCDE"))

In [16]:
df

    A  B  C  D  E
0   0  3  2  5  3
1   3  5  9  3  2
2   7  1  6  2  6
3   8  4  6  0  6
4   5  3  5  9  4
5   2  7  5  5  1
6   2  4  4  5  7
7   0  2  0  6  1
8   3  2  4  7  0
9   1  2  8  6  4
10  9  0  6  3  4
11  8  5  7  6  1
12  8  1  8  3  8
13  9  7  8  0  2
14  6  8  9  4  8
15  1  4  9  5  5
16  1  9  6  7  3
17  1  2  9  1  3
18  3  8  8  9  1
19  1  0  9  6  0

In [17]:
df.A.value_counts()

1    5
8    3
3    3
9    2
2    2
0    2
7    1
6    1
5    1
Name: A, dtype: int64

<h1>Concatenation</h1>

In [18]:
df1 = pd.DataFrame({
    'A':[10,20,30,40],
    'B':["test","train","test","train"]
})

In [19]:
df1

    A      B
0  10   test
1  20  train
2  30   test
3  40  train

In [20]:
df2 = pd.DataFrame({
    'C':[100,200,300,400],
    'D':["Apple","Mango","Banana","Grapes"]
})

In [21]:
df2

     C       D
0  100   Apple
1  200   Mango
2  300  Banana
3  400  Grapes

In [22]:
pd.concat((df1,df2))

      A      B      C       D
0  10.0   test    NaN     NaN
1  20.0  train    NaN     NaN
2  30.0   test    NaN     NaN
3  40.0  train    NaN     NaN
0   NaN    NaN  100.0   Apple
1   NaN    NaN  200.0   Mango
2   NaN    NaN  300.0  Banana
3   NaN    NaN  400.0  Grapes

In [23]:
pd.concat((df1,df2),axis=1)

    A      B    C       D
0  10   test  100   Apple
1  20  train  200   Mango
2  30   test  300  Banana
3  40  train  400  Grapes

<h1>Join</h1>

In [24]:
df1 = pd.DataFrame({
    "fruits":["Apple","Mango","Orange"],
    "Price":[100,200,89]
})

In [25]:
df2 = pd.DataFrame({
    "fruits":["Apple","Mango","Orange","Banana"],
    "Price":[100,200,30,45]
})

In [26]:
df1

   fruits  Price
0   Apple    100
1   Mango    200
2  Orange     89

In [27]:
df2

   fruits  Price
0   Apple    100
1   Mango    200
2  Orange     30
3  Banana     45

In [28]:
pd.merge(df1,df2,on="fruits")

   fruits  Price_x  Price_y
0   Apple      100      100
1   Mango      200      200
2  Orange       89       30

In [29]:
pd.merge(df1,df2)

  fruits  Price
0  Apple    100
1  Mango    200

In [30]:
pd.merge(df1,df2,how="outer")

   fruits  Price
0   Apple    100
1   Mango    200
2  Orange     89
3  Orange     30
4  Banana     45

In [31]:
pd.merge(df1,df2,how="left")

   fruits  Price
0   Apple    100
1   Mango    200
2  Orange     89

In [32]:
pd.merge(df1,df2,how="right")

   fruits  Price
0   Apple    100
1   Mango    200
2  Orange     30
3  Banana     45

Grouping

By “group by” we are referring to a process involving one or more of the following steps:

- Splitting the data into groups based on some criteria

- Applying a function to each group independently

- Combining the results into a data structure

In [33]:
df = pd.DataFrame({
    'A':["foo","bar"]*4,
    'B':["one", "one", "two", "three", "two", "two", "one", "three"],
    'C':np.random.randn(8),
    'D':np.random.randn(8)
})

In [34]:
df

     A      B         C         D
0  foo    one -0.993819  0.038359
1  bar    one  1.469631 -0.238722
2  foo    two  1.770110  0.695718
3  bar  three -0.174137  0.164947
4  foo    two -0.345612 -0.127493
5  bar    two  1.216709 -0.362208
6  foo    one  1.539462 -0.333237
7  bar  three -0.541850 -0.703716

In [35]:
list(df.groupby("A"))

[('bar',      A      B         C         D
  1  bar    one  1.469631 -0.238722
  3  bar  three -0.174137  0.164947
  5  bar    two  1.216709 -0.362208
  7  bar  three -0.541850 -0.703716), ('foo',      A    B         C         D
  0  foo  one -0.993819  0.038359
  2  foo  two  1.770110  0.695718
  4  foo  two -0.345612 -0.127493
  6  foo  one  1.539462 -0.333237)]

In [36]:
df.groupby("A").sum()

            C         D
A
bar  1.970353 -1.139699
foo  1.970140  0.273347

In [37]:
df.groupby("B").sum()

              C         D
B
one    2.015274 -0.533600
three -0.715987 -0.538769
two    2.641207  0.206017

In [38]:
df.groupby("B").sum().T

B       one     three       two
C  2.015274 -0.715987  2.641207
D -0.533600 -0.538769  0.206017