In [1]:
import numpy as np
import pandas as pd

Creating a DataFrame by passing a dictionary of objects that can be converted into a series-like structure:

In [2]:
df = pd.DataFrame({
    'Name':["Ram","shyam","Sita","Gita"],
    'Age':[10,11,12,13],
    'College':'ABC secondary'

})

In [3]:
df

    Name  Age        College
0    Ram   10  ABC secondary
1  shyam   11  ABC secondary
2   Sita   12  ABC secondary
3   Gita   13  ABC secondary

In [4]:
df2 = pd.DataFrame({
    'A':1.0,
    'B':pd.Timestamp('20220127'),
    'C':pd.Series(1,index=list(range(4)),dtype=np.float32),
    'D':np.array([3]*4,dtype=np.int32),
    'E':pd.Categorical(["test","train","test","train"]),
    'F':"foo"
})

In [5]:
df2

     A          B    C  D      E    F
0  1.0 2022-01-27  1.0  3   test  foo
1  1.0 2022-01-27  1.0  3  train  foo
2  1.0 2022-01-27  1.0  3   test  foo
3  1.0 2022-01-27  1.0  3  train  foo

The columns of the resulting DataFrame have different dtypes:

In [6]:
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

To view the top and bottom rows of the frame:

In [7]:
df = pd.DataFrame(data=np.random.randn(6,4),index=pd.date_range(start="20220120",periods=6),columns=list("ABCD"))

In [8]:
df

                   A         B         C         D
2022-01-20 -1.113900 -1.927744 -0.383048  1.170159
2022-01-21  2.080596 -0.538064  0.722640 -1.704476
2022-01-22  0.563289 -0.322391 -1.723926 -0.094348
2022-01-23 -0.857332  0.033179  1.284216 -1.214974
2022-01-24  1.252785 -1.251117 -0.283401  0.839884
2022-01-25 -2.179340 -0.281591 -0.357418 -0.847597

In [9]:
df.head(2)

                   A         B         C         D
2022-01-20 -1.113900 -1.927744 -0.383048  1.170159
2022-01-21  2.080596 -0.538064  0.722640 -1.704476

In [10]:
df.tail(2)

                   A         B         C         D
2022-01-24  1.252785 -1.251117 -0.283401  0.839884
2022-01-25 -2.179340 -0.281591 -0.357418 -0.847597

Display the index, columns:

In [11]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [12]:
df.index

DatetimeIndex(['2022-01-20', '2022-01-21', '2022-01-22', '2022-01-23',
               '2022-01-24', '2022-01-25'],
              dtype='datetime64[ns]', freq='D')

In [13]:
df.to_numpy()

array([[-1.11390033, -1.92774433, -0.3830478 ,  1.17015916],
       [ 2.08059601, -0.53806383,  0.7226402 , -1.7044762 ],
       [ 0.5632886 , -0.32239101, -1.7239257 , -0.0943483 ],
       [-0.85733163,  0.03317937,  1.28421606, -1.21497382],
       [ 1.25278477, -1.25111717, -0.28340101,  0.8398836 ],
       [-2.17934026, -0.28159056, -0.35741848, -0.84759714]])

In [14]:
df2.to_numpy()

array([[1.0, Timestamp('2022-01-27 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2022-01-27 00:00:00'), 1.0, 3, 'train', 'foo'],
       [1.0, Timestamp('2022-01-27 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2022-01-27 00:00:00'), 1.0, 3, 'train', 'foo']],
      dtype=object)

describe() shows a quick statistic summary of your data:

In [15]:
df.describe()

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.042317 -0.714621 -0.123489 -0.308559
std    1.608118  0.733653  1.039868  1.149969
min   -2.179340 -1.927744 -1.723926 -1.704476
25%   -1.049758 -1.072854 -0.376640 -1.123130
50%   -0.147022 -0.430227 -0.320410 -0.470973
75%    1.080411 -0.291791  0.471130  0.606326
max    2.080596  0.033179  1.284216  1.170159

In [16]:
df2.describe()

         A    C    D
count  4.0  4.0  4.0
mean   1.0  1.0  3.0
std    0.0  0.0  0.0
min    1.0  1.0  3.0
25%    1.0  1.0  3.0
50%    1.0  1.0  3.0
75%    1.0  1.0  3.0
max    1.0  1.0  3.0

Transposing your data:

In [17]:
df.T

   2022-01-20  2022-01-21  2022-01-22  2022-01-23  2022-01-24  2022-01-25
A   -1.113900    2.080596    0.563289   -0.857332    1.252785   -2.179340
B   -1.927744   -0.538064   -0.322391    0.033179   -1.251117   -0.281591
C   -0.383048    0.722640   -1.723926    1.284216   -0.283401   -0.357418
D    1.170159   -1.704476   -0.094348   -1.214974    0.839884   -0.847597

In [18]:
df2.T

                     0  ...                    3
A                    1  ...                    1
B  2022-01-27 00:00:00  ...  2022-01-27 00:00:00
C                    1  ...                    1
D                    3  ...                    3
E                 test  ...                train
F                  foo  ...                  foo

[6 rows x 4 columns]

In [19]:
dummy_df = pd.DataFrame({
    'Name':["Ram","shyam","Sita","Gita"],
    'Age':[10,11,12,13],
    'College':'ABC secondary'

})

Sorting by an axis:

In [20]:
dummy_df

    Name  Age        College
0    Ram   10  ABC secondary
1  shyam   11  ABC secondary
2   Sita   12  ABC secondary
3   Gita   13  ABC secondary

In [21]:
dummy_df.sort_index(axis=1,ascending=False) # axis=1, represents columns

    Name        College  Age
0    Ram  ABC secondary   10
1  shyam  ABC secondary   11
2   Sita  ABC secondary   12
3   Gita  ABC secondary   13

In [22]:
df.sort_index(axis=1,ascending=False)

                   D         C         B         A
2022-01-20  1.170159 -0.383048 -1.927744 -1.113900
2022-01-21 -1.704476  0.722640 -0.538064  2.080596
2022-01-22 -0.094348 -1.723926 -0.322391  0.563289
2022-01-23 -1.214974  1.284216  0.033179 -0.857332
2022-01-24  0.839884 -0.283401 -1.251117  1.252785
2022-01-25 -0.847597 -0.357418 -0.281591 -2.179340

In [23]:
dummy_df.sort_index(axis=0,ascending=False) # axis=0, represents rows

    Name  Age        College
3   Gita   13  ABC secondary
2   Sita   12  ABC secondary
1  shyam   11  ABC secondary
0    Ram   10  ABC secondary

In [24]:
df.sort_index(axis=1,ascending=False)

                   D         C         B         A
2022-01-20  1.170159 -0.383048 -1.927744 -1.113900
2022-01-21 -1.704476  0.722640 -0.538064  2.080596
2022-01-22 -0.094348 -1.723926 -0.322391  0.563289
2022-01-23 -1.214974  1.284216  0.033179 -0.857332
2022-01-24  0.839884 -0.283401 -1.251117  1.252785
2022-01-25 -0.847597 -0.357418 -0.281591 -2.179340

Sorting by values:

In [25]:
df

                   A         B         C         D
2022-01-20 -1.113900 -1.927744 -0.383048  1.170159
2022-01-21  2.080596 -0.538064  0.722640 -1.704476
2022-01-22  0.563289 -0.322391 -1.723926 -0.094348
2022-01-23 -0.857332  0.033179  1.284216 -1.214974
2022-01-24  1.252785 -1.251117 -0.283401  0.839884
2022-01-25 -2.179340 -0.281591 -0.357418 -0.847597

In [26]:
df.sort_values(by='A')

                   A         B         C         D
2022-01-25 -2.179340 -0.281591 -0.357418 -0.847597
2022-01-20 -1.113900 -1.927744 -0.383048  1.170159
2022-01-23 -0.857332  0.033179  1.284216 -1.214974
2022-01-22  0.563289 -0.322391 -1.723926 -0.094348
2022-01-24  1.252785 -1.251117 -0.283401  0.839884
2022-01-21  2.080596 -0.538064  0.722640 -1.704476

In [27]:
df.sort_values(by='A',ascending=False)

                   A         B         C         D
2022-01-21  2.080596 -0.538064  0.722640 -1.704476
2022-01-24  1.252785 -1.251117 -0.283401  0.839884
2022-01-22  0.563289 -0.322391 -1.723926 -0.094348
2022-01-23 -0.857332  0.033179  1.284216 -1.214974
2022-01-20 -1.113900 -1.927744 -0.383048  1.170159
2022-01-25 -2.179340 -0.281591 -0.357418 -0.847597

Selection

Selecting a single column, which yields a Series,

In [28]:
df["A"]

2022-01-20   -1.113900
2022-01-21    2.080596
2022-01-22    0.563289
2022-01-23   -0.857332
2022-01-24    1.252785
2022-01-25   -2.179340
Freq: D, Name: A, dtype: float64

Selecting via [ ], which slices the rows:

In [29]:
df[:3]

                   A         B         C         D
2022-01-20 -1.113900 -1.927744 -0.383048  1.170159
2022-01-21  2.080596 -0.538064  0.722640 -1.704476
2022-01-22  0.563289 -0.322391 -1.723926 -0.094348

In [30]:
dummy_df[:2]

    Name  Age        College
0    Ram   10  ABC secondary
1  shyam   11  ABC secondary

Selection by label


For getting a cross section using a label:

In [31]:
indices = df.index.values

In [32]:
df

                   A         B         C         D
2022-01-20 -1.113900 -1.927744 -0.383048  1.170159
2022-01-21  2.080596 -0.538064  0.722640 -1.704476
2022-01-22  0.563289 -0.322391 -1.723926 -0.094348
2022-01-23 -0.857332  0.033179  1.284216 -1.214974
2022-01-24  1.252785 -1.251117 -0.283401  0.839884
2022-01-25 -2.179340 -0.281591 -0.357418 -0.847597

In [33]:
df.loc[indices[0]]

A   -1.113900
B   -1.927744
C   -0.383048
D    1.170159
Name: 2022-01-20 00:00:00, dtype: float64

In [34]:
dummy_df.loc[dummy_df.index[0]]

Name                 Ram
Age                   10
College    ABC secondary
Name: 0, dtype: object

Selecting on a multi-axis by label:

In [35]:
dummy_df.loc[:,["Name","Age"]]

    Name  Age
0    Ram   10
1  shyam   11
2   Sita   12
3   Gita   13

In [36]:
df.loc[:,["A","B"]]

                   A         B
2022-01-20 -1.113900 -1.927744
2022-01-21  2.080596 -0.538064
2022-01-22  0.563289 -0.322391
2022-01-23 -0.857332  0.033179
2022-01-24  1.252785 -1.251117
2022-01-25 -2.179340 -0.281591

In [37]:
dummy_df

    Name  Age        College
0    Ram   10  ABC secondary
1  shyam   11  ABC secondary
2   Sita   12  ABC secondary
3   Gita   13  ABC secondary

In [38]:
dummy_df.loc[0:2,["Name","College"]]

    Name        College
0    Ram  ABC secondary
1  shyam  ABC secondary
2   Sita  ABC secondary

In [39]:
dummy_df.loc[0,["Name"]]

Name    Ram
Name: 0, dtype: object

For getting fast access to a scalar

In [40]:
dummy_df.at[1,"Age"]

11

Selection by position

Select via the position of the passed integers:

In [41]:
df

                   A         B         C         D
2022-01-20 -1.113900 -1.927744 -0.383048  1.170159
2022-01-21  2.080596 -0.538064  0.722640 -1.704476
2022-01-22  0.563289 -0.322391 -1.723926 -0.094348
2022-01-23 -0.857332  0.033179  1.284216 -1.214974
2022-01-24  1.252785 -1.251117 -0.283401  0.839884
2022-01-25 -2.179340 -0.281591 -0.357418 -0.847597

In [42]:
df.iloc[2]

A    0.563289
B   -0.322391
C   -1.723926
D   -0.094348
Name: 2022-01-22 00:00:00, dtype: float64

In [43]:
df.iloc[3]

A   -0.857332
B    0.033179
C    1.284216
D   -1.214974
Name: 2022-01-23 00:00:00, dtype: float64

By integer slices, acting similar to NumPy/Python:

In [44]:
df.iloc[:,0:2]

                   A         B
2022-01-20 -1.113900 -1.927744
2022-01-21  2.080596 -0.538064
2022-01-22  0.563289 -0.322391
2022-01-23 -0.857332  0.033179
2022-01-24  1.252785 -1.251117
2022-01-25 -2.179340 -0.281591

In [45]:
df.iloc[2:4,:]

                   A         B         C         D
2022-01-22  0.563289 -0.322391 -1.723926 -0.094348
2022-01-23 -0.857332  0.033179  1.284216 -1.214974

By lists of integer position locations, similar to the NumPy/Python style:

In [46]:
dummy_df.iloc[[1,2],[0,1]]

    Name  Age
1  shyam   11
2   Sita   12

For slicing rows explicitly:

In [47]:
dummy_df.iloc[1:2,:]

    Name  Age        College
1  shyam   11  ABC secondary

For slicing columns explicitly:

In [48]:
dummy_df.iloc[:,0:2]

    Name  Age
0    Ram   10
1  shyam   11
2   Sita   12
3   Gita   13

In [49]:
df.iat[1,1]

-0.5380638312207967

Boolean indexing

In [50]:
df

                   A         B         C         D
2022-01-20 -1.113900 -1.927744 -0.383048  1.170159
2022-01-21  2.080596 -0.538064  0.722640 -1.704476
2022-01-22  0.563289 -0.322391 -1.723926 -0.094348
2022-01-23 -0.857332  0.033179  1.284216 -1.214974
2022-01-24  1.252785 -1.251117 -0.283401  0.839884
2022-01-25 -2.179340 -0.281591 -0.357418 -0.847597

In [51]:
df>0

                A      B      C      D
2022-01-20  False  False  False   True
2022-01-21   True  False   True  False
2022-01-22   True  False  False  False
2022-01-23  False   True   True  False
2022-01-24   True  False  False   True
2022-01-25  False  False  False  False

In [52]:
# Selecting values from a DataFrame where a boolean condition is met:
df[df>0]

                   A         B         C         D
2022-01-20       NaN       NaN       NaN  1.170159
2022-01-21  2.080596       NaN  0.722640       NaN
2022-01-22  0.563289       NaN       NaN       NaN
2022-01-23       NaN  0.033179  1.284216       NaN
2022-01-24  1.252785       NaN       NaN  0.839884
2022-01-25       NaN       NaN       NaN       NaN

In [53]:
dummy_df

    Name  Age        College
0    Ram   10  ABC secondary
1  shyam   11  ABC secondary
2   Sita   12  ABC secondary
3   Gita   13  ABC secondary

Using the isin() method for filtering:

In [54]:
dummy_df[dummy_df.isin(["Ram"])]

  Name  Age College
0  Ram  NaN     NaN
1  NaN  NaN     NaN
2  NaN  NaN     NaN
3  NaN  NaN     NaN

In [55]:
dummy_df[dummy_df["Name"].isin(["Ram"])]

  Name  Age        College
0  Ram   10  ABC secondary

Setting

Setting a new column automatically aligns the data by the indexes:

In [56]:
dummy_df

    Name  Age        College
0    Ram   10  ABC secondary
1  shyam   11  ABC secondary
2   Sita   12  ABC secondary
3   Gita   13  ABC secondary

In [57]:
dummy_df['Marks'] = [20.45,33.56,45,89]

In [58]:
dummy_df

    Name  Age        College  Marks
0    Ram   10  ABC secondary  20.45
1  shyam   11  ABC secondary  33.56
2   Sita   12  ABC secondary  45.00
3   Gita   13  ABC secondary  89.00

Missing data


pandas primarily uses the value np.nan to represent missing data. It is by default not included in computations.

Reindexing allows you to change/add/delete the index on a specified axis. This returns a copy of the data:

In [59]:
df

                   A         B         C         D
2022-01-20 -1.113900 -1.927744 -0.383048  1.170159
2022-01-21  2.080596 -0.538064  0.722640 -1.704476
2022-01-22  0.563289 -0.322391 -1.723926 -0.094348
2022-01-23 -0.857332  0.033179  1.284216 -1.214974
2022-01-24  1.252785 -1.251117 -0.283401  0.839884
2022-01-25 -2.179340 -0.281591 -0.357418 -0.847597

In [60]:
df3 = df.reindex(index=pd.date_range("2022-01-20",periods=4),columns=list(df.columns)+["E"])

In [61]:
df3

                   A         B         C         D   E
2022-01-20 -1.113900 -1.927744 -0.383048  1.170159 NaN
2022-01-21  2.080596 -0.538064  0.722640 -1.704476 NaN
2022-01-22  0.563289 -0.322391 -1.723926 -0.094348 NaN
2022-01-23 -0.857332  0.033179  1.284216 -1.214974 NaN

In [62]:
df3.loc[:2,"E"] = 1

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Slicing a positional slice with .loc is not supported, and will raise TypeError in a future version.  Use .loc with labels or .iloc with positions instead.
  """Entry point for launching an IPython kernel.

In [63]:
df3

                   A         B         C         D    E
2022-01-20 -1.113900 -1.927744 -0.383048  1.170159  1.0
2022-01-21  2.080596 -0.538064  0.722640 -1.704476  1.0
2022-01-22  0.563289 -0.322391 -1.723926 -0.094348  NaN
2022-01-23 -0.857332  0.033179  1.284216 -1.214974  NaN

To drop any rows that have missing data:

In [64]:
df3.isna()

                A      B      C      D      E
2022-01-20  False  False  False  False  False
2022-01-21  False  False  False  False  False
2022-01-22  False  False  False  False   True
2022-01-23  False  False  False  False   True

In [65]:
df3.isna().sum()

A    0
B    0
C    0
D    0
E    2
dtype: int64

In [66]:
df3.dropna(how='any')

                   A         B         C         D    E
2022-01-20 -1.113900 -1.927744 -0.383048  1.170159  1.0
2022-01-21  2.080596 -0.538064  0.722640 -1.704476  1.0

In [67]:
df3

                   A         B         C         D    E
2022-01-20 -1.113900 -1.927744 -0.383048  1.170159  1.0
2022-01-21  2.080596 -0.538064  0.722640 -1.704476  1.0
2022-01-22  0.563289 -0.322391 -1.723926 -0.094348  NaN
2022-01-23 -0.857332  0.033179  1.284216 -1.214974  NaN

In [68]:
df3.dropna(axis=0)

                   A         B         C         D    E
2022-01-20 -1.113900 -1.927744 -0.383048  1.170159  1.0
2022-01-21  2.080596 -0.538064  0.722640 -1.704476  1.0

In [69]:
df3.dropna(axis=1)

                   A         B         C         D
2022-01-20 -1.113900 -1.927744 -0.383048  1.170159
2022-01-21  2.080596 -0.538064  0.722640 -1.704476
2022-01-22  0.563289 -0.322391 -1.723926 -0.094348
2022-01-23 -0.857332  0.033179  1.284216 -1.214974

In [70]:
df3.fillna(value=np.mean(df3['E']))

                   A         B         C         D    E
2022-01-20 -1.113900 -1.927744 -0.383048  1.170159  1.0
2022-01-21  2.080596 -0.538064  0.722640 -1.704476  1.0
2022-01-22  0.563289 -0.322391 -1.723926 -0.094348  1.0
2022-01-23 -0.857332  0.033179  1.284216 -1.214974  1.0

Operations

Operations in general exclude missing data.

Performing a descriptive statistic:

In [71]:
df3

                   A         B         C         D    E
2022-01-20 -1.113900 -1.927744 -0.383048  1.170159  1.0
2022-01-21  2.080596 -0.538064  0.722640 -1.704476  1.0
2022-01-22  0.563289 -0.322391 -1.723926 -0.094348  NaN
2022-01-23 -0.857332  0.033179  1.284216 -1.214974  NaN

In [72]:
df3.mean()

A    0.168163
B   -0.688755
C   -0.025029
D   -0.460910
E    1.000000
dtype: float64

In [73]:
df3.mean(axis=1)

2022-01-20   -0.250907
2022-01-21    0.312139
2022-01-22   -0.394344
2022-01-23   -0.188728
Freq: D, dtype: float64

In [74]:
df3.mean(axis=0)

A    0.168163
B   -0.688755
C   -0.025029
D   -0.460910
E    1.000000
dtype: float64

Apply

Applying functions to the data:

In [75]:
s_df = pd.DataFrame(data=[[4,9]]*3,columns=["A","B"])

In [76]:
s_df

   A  B
0  4  9
1  4  9
2  4  9

In [77]:
s_df.apply(np.sqrt)

     A    B
0  2.0  3.0
1  2.0  3.0
2  2.0  3.0

In [78]:
def test(x):
  return x*x

In [79]:
s_df.apply(test)

    A   B
0  16  81
1  16  81
2  16  81

In [80]:
dummy_df

    Name  Age        College  Marks
0    Ram   10  ABC secondary  20.45
1  shyam   11  ABC secondary  33.56
2   Sita   12  ABC secondary  45.00
3   Gita   13  ABC secondary  89.00

In [81]:
def get_sum(st):
  return st.sum()

dummy_df.apply(get_sum)

Name                                        RamshyamSitaGita
Age                                                       46
College    ABC secondaryABC secondaryABC secondaryABC sec...
Marks                                                 188.01
dtype: object

In [82]:
df

                   A         B         C         D
2022-01-20 -1.113900 -1.927744 -0.383048  1.170159
2022-01-21  2.080596 -0.538064  0.722640 -1.704476
2022-01-22  0.563289 -0.322391 -1.723926 -0.094348
2022-01-23 -0.857332  0.033179  1.284216 -1.214974
2022-01-24  1.252785 -1.251117 -0.283401  0.839884
2022-01-25 -2.179340 -0.281591 -0.357418 -0.847597

In [83]:
df.apply(np.sum,axis=0)

A   -0.253903
B   -4.287728
C   -0.740937
D   -1.851353
dtype: float64

In [84]:
df.apply(np.sum,axis=1)

2022-01-20   -2.254533
2022-01-21    0.560696
2022-01-22   -1.577376
2022-01-23   -0.754910
2022-01-24    0.558150
2022-01-25   -3.665946
Freq: D, dtype: float64

Histogramming

In [85]:
x = pd.Series(data=np.random.randint(0,6,size=20))

In [86]:
x

0     1
1     4
2     3
3     3
4     5
5     3
6     3
7     1
8     1
9     2
10    4
11    3
12    4
13    4
14    4
15    4
16    1
17    2
18    1
19    0
dtype: int64

In [87]:
x.value_counts()

4    6
3    5
1    5
2    2
5    1
0    1
dtype: int64

Join

SQL style merges.

In [88]:
d1 = pd.DataFrame({
    "Product":["Apple","Oranges"],
    "Prices":[10,11]
})

In [89]:
d1

   Product  Prices
0    Apple      10
1  Oranges      11

In [90]:
d2 = pd.DataFrame({
    "Product":["Apple","Oranges","Mango"],
    "Prices":[10,11,12]
})

In [91]:
d2

   Product  Prices
0    Apple      10
1  Oranges      11
2    Mango      12

In [92]:
pd.merge(d1,d2,how="inner",on="Product")

   Product  Prices_x  Prices_y
0    Apple        10        10
1  Oranges        11        11

In [93]:
pd.merge(d1,d2,how="outer",on="Product")

   Product  Prices_x  Prices_y
0    Apple      10.0        10
1  Oranges      11.0        11
2    Mango       NaN        12