**What is Pandas?**

- Pandas is a Python library used for working with data sets.

- It has functions for analyzing, cleaning, exploring, and manipulating data.

- The name "Pandas" has a reference to both "Panel Data", and "Python Data Analysis" and was created by Wes McKinney in 2008.

**Why Use Pandas?**

- Pandas allows us to analyze big data and make conclusions based on statistical theories.

- Pandas can clean messy data sets, and make them readable and relevant.

- Relevant data is very important in data science.

In [1]:
import numpy as np
import pandas as pd

**Series**

Series is a one-dimensional labeled array capable of holding any data type (integers, strings, floating point numbers, Python objects, etc.). The axis labels are collectively referred to as the index.

In [2]:
s = pd.Series([1,3,5,np.nan,6,8])

In [3]:
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [5]:
s.values

array([ 1.,  3.,  5., nan,  6.,  8.])

In [6]:
s.index

RangeIndex(start=0, stop=6, step=1)

**Pandas DataFrame**

Pandas DataFrame is two-dimensional size-mutable, potentially heterogeneous tabular data structure with labeled axes (rows and columns). A Data frame is a two-dimensional data structure, i.e., data is aligned in a tabular fashion in rows and columns. Pandas DataFrame consists of three principal components, the data, rows, and columns.


Creating a DataFrame by passing a NumPy array, with a datetime index and labeled columns:

In [9]:
dates = pd.date_range(start="20220120",periods=6)

In [10]:
dates

DatetimeIndex(['2022-01-20', '2022-01-21', '2022-01-22', '2022-01-23',
               '2022-01-24', '2022-01-25'],
              dtype='datetime64[ns]', freq='D')

In [11]:
np.random.randn(6,4)

array([[ 1.12169801,  0.96406457, -0.70818795, -0.18411195],
       [-0.72609225,  0.37812147, -0.50629216, -1.22697134],
       [-0.52063325, -0.02584939,  1.5355422 , -0.93727285],
       [ 1.36175442,  0.27468511,  0.12042312, -1.61180138],
       [-1.46086598,  0.90755496,  0.85579221,  0.23188374],
       [ 0.02640298,  0.83485265,  2.60502125,  0.76150875]])

In [12]:
df = pd.DataFrame(data=np.random.randn(6,4),index=dates,columns=list("ABCD"))

In [14]:
df

                   A         B         C         D
2022-01-20 -0.664715  0.499887  1.752984 -0.719964
2022-01-21 -0.277661  1.479432 -0.508587 -1.293311
2022-01-22  0.396932 -0.186641 -1.430746 -0.426380
2022-01-23  0.856612  1.077370  1.035712  0.452761
2022-01-24 -1.342926 -0.042383  1.180479 -1.763657
2022-01-25  0.467133  0.080259 -0.558254 -0.557239

Creating a DataFrame by passing a dictionary of objects that can be converted into a series-like structure:

In [15]:
df2 = pd.DataFrame({
    'A':1.0,
    'B':pd.Timestamp('20220101'),
    'C':pd.Series(1,index=list(range(4)),dtype=np.float32),
    'D':np.array([3]*4,dtype=np.int32),
    'E':pd.Categorical(["test","train","test","train"]),
    'F':"foo"
})

In [16]:
df2

     A          B    C  D      E    F
0  1.0 2022-01-01  1.0  3   test  foo
1  1.0 2022-01-01  1.0  3  train  foo
2  1.0 2022-01-01  1.0  3   test  foo
3  1.0 2022-01-01  1.0  3  train  foo

The columns of the resulting DataFrame have different dtypes:

In [17]:
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

**Viewing data**

Here is how to view the top and bottom rows of the frame:

In [18]:
df2.head()

     A          B    C  D      E    F
0  1.0 2022-01-01  1.0  3   test  foo
1  1.0 2022-01-01  1.0  3  train  foo
2  1.0 2022-01-01  1.0  3   test  foo
3  1.0 2022-01-01  1.0  3  train  foo

In [19]:
df2.tail()

     A          B    C  D      E    F
0  1.0 2022-01-01  1.0  3   test  foo
1  1.0 2022-01-01  1.0  3  train  foo
2  1.0 2022-01-01  1.0  3   test  foo
3  1.0 2022-01-01  1.0  3  train  foo

In [21]:
#view index of dataframe

df2.index

Int64Index([0, 1, 2, 3], dtype='int64')

In [22]:
#list column names
df2.columns

Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='object')

In [23]:
df2.to_numpy()

array([[1.0, Timestamp('2022-01-01 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2022-01-01 00:00:00'), 1.0, 3, 'train', 'foo'],
       [1.0, Timestamp('2022-01-01 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2022-01-01 00:00:00'), 1.0, 3, 'train', 'foo']],
      dtype=object)

describe() shows a quick statistic summary of your data:

In [24]:
df2.describe()

         A    C    D
count  4.0  4.0  4.0
mean   1.0  1.0  3.0
std    0.0  0.0  0.0
min    1.0  1.0  3.0
25%    1.0  1.0  3.0
50%    1.0  1.0  3.0
75%    1.0  1.0  3.0
max    1.0  1.0  3.0

Transposing your data:

In [25]:
df2.T

                     0  ...                    3
A                    1  ...                    1
B  2022-01-01 00:00:00  ...  2022-01-01 00:00:00
C                    1  ...                    1
D                    3  ...                    3
E                 test  ...                train
F                  foo  ...                  foo

[6 rows x 4 columns]

sorting dataframe

In [26]:
df

                   A         B         C         D
2022-01-20 -0.664715  0.499887  1.752984 -0.719964
2022-01-21 -0.277661  1.479432 -0.508587 -1.293311
2022-01-22  0.396932 -0.186641 -1.430746 -0.426380
2022-01-23  0.856612  1.077370  1.035712  0.452761
2022-01-24 -1.342926 -0.042383  1.180479 -1.763657
2022-01-25  0.467133  0.080259 -0.558254 -0.557239

**SORT BY INDEX**

In [27]:
df.sort_index(axis=1,ascending=False) #column-wise sorting

                   D         C         B         A
2022-01-20 -0.719964  1.752984  0.499887 -0.664715
2022-01-21 -1.293311 -0.508587  1.479432 -0.277661
2022-01-22 -0.426380 -1.430746 -0.186641  0.396932
2022-01-23  0.452761  1.035712  1.077370  0.856612
2022-01-24 -1.763657  1.180479 -0.042383 -1.342926
2022-01-25 -0.557239 -0.558254  0.080259  0.467133

In [28]:
df.sort_index(axis=0,ascending=False) #row-wise sorting

                   A         B         C         D
2022-01-25  0.467133  0.080259 -0.558254 -0.557239
2022-01-24 -1.342926 -0.042383  1.180479 -1.763657
2022-01-23  0.856612  1.077370  1.035712  0.452761
2022-01-22  0.396932 -0.186641 -1.430746 -0.426380
2022-01-21 -0.277661  1.479432 -0.508587 -1.293311
2022-01-20 -0.664715  0.499887  1.752984 -0.719964

**SORT BY VALUES**

In [29]:
df

                   A         B         C         D
2022-01-20 -0.664715  0.499887  1.752984 -0.719964
2022-01-21 -0.277661  1.479432 -0.508587 -1.293311
2022-01-22  0.396932 -0.186641 -1.430746 -0.426380
2022-01-23  0.856612  1.077370  1.035712  0.452761
2022-01-24 -1.342926 -0.042383  1.180479 -1.763657
2022-01-25  0.467133  0.080259 -0.558254 -0.557239

In [30]:
df.sort_values(by='A')

                   A         B         C         D
2022-01-24 -1.342926 -0.042383  1.180479 -1.763657
2022-01-20 -0.664715  0.499887  1.752984 -0.719964
2022-01-21 -0.277661  1.479432 -0.508587 -1.293311
2022-01-22  0.396932 -0.186641 -1.430746 -0.426380
2022-01-25  0.467133  0.080259 -0.558254 -0.557239
2022-01-23  0.856612  1.077370  1.035712  0.452761

In [31]:
df

                   A         B         C         D
2022-01-20 -0.664715  0.499887  1.752984 -0.719964
2022-01-21 -0.277661  1.479432 -0.508587 -1.293311
2022-01-22  0.396932 -0.186641 -1.430746 -0.426380
2022-01-23  0.856612  1.077370  1.035712  0.452761
2022-01-24 -1.342926 -0.042383  1.180479 -1.763657
2022-01-25  0.467133  0.080259 -0.558254 -0.557239

In [32]:
df.sort_values(by='D',ascending=False)

                   A         B         C         D
2022-01-23  0.856612  1.077370  1.035712  0.452761
2022-01-22  0.396932 -0.186641 -1.430746 -0.426380
2022-01-25  0.467133  0.080259 -0.558254 -0.557239
2022-01-20 -0.664715  0.499887  1.752984 -0.719964
2022-01-21 -0.277661  1.479432 -0.508587 -1.293311
2022-01-24 -1.342926 -0.042383  1.180479 -1.763657

**SELECTION**

Selecting a single column, which yields a Series, equivalent to df.A:

In [33]:
df.A

2022-01-20   -0.664715
2022-01-21   -0.277661
2022-01-22    0.396932
2022-01-23    0.856612
2022-01-24   -1.342926
2022-01-25    0.467133
Freq: D, Name: A, dtype: float64

In [34]:
df["A"]

2022-01-20   -0.664715
2022-01-21   -0.277661
2022-01-22    0.396932
2022-01-23    0.856612
2022-01-24   -1.342926
2022-01-25    0.467133
Freq: D, Name: A, dtype: float64

Selecting via [], which slices the rows:

In [35]:
df

                   A         B         C         D
2022-01-20 -0.664715  0.499887  1.752984 -0.719964
2022-01-21 -0.277661  1.479432 -0.508587 -1.293311
2022-01-22  0.396932 -0.186641 -1.430746 -0.426380
2022-01-23  0.856612  1.077370  1.035712  0.452761
2022-01-24 -1.342926 -0.042383  1.180479 -1.763657
2022-01-25  0.467133  0.080259 -0.558254 -0.557239

In [36]:
df[0:3]

                   A         B         C         D
2022-01-20 -0.664715  0.499887  1.752984 -0.719964
2022-01-21 -0.277661  1.479432 -0.508587 -1.293311
2022-01-22  0.396932 -0.186641 -1.430746 -0.426380

In [37]:
df["2022-01-22":]

                   A         B         C         D
2022-01-22  0.396932 -0.186641 -1.430746 -0.426380
2022-01-23  0.856612  1.077370  1.035712  0.452761
2022-01-24 -1.342926 -0.042383  1.180479 -1.763657
2022-01-25  0.467133  0.080259 -0.558254 -0.557239

In [38]:
df["2022-01-22":"2022-01-24"]

                   A         B         C         D
2022-01-22  0.396932 -0.186641 -1.430746 -0.426380
2022-01-23  0.856612  1.077370  1.035712  0.452761
2022-01-24 -1.342926 -0.042383  1.180479 -1.763657

**Selection by label**

In [39]:
dates

DatetimeIndex(['2022-01-20', '2022-01-21', '2022-01-22', '2022-01-23',
               '2022-01-24', '2022-01-25'],
              dtype='datetime64[ns]', freq='D')

In [41]:
dates[0]

Timestamp('2022-01-20 00:00:00', freq='D')

In [43]:
# For getting a cross section using a label:

df.loc[dates[0]]

A   -0.664715
B    0.499887
C    1.752984
D   -0.719964
Name: 2022-01-20 00:00:00, dtype: float64

In [44]:
# For getting a cross section using a label:

df.loc[:,["A","B"]]

                   A         B
2022-01-20 -0.664715  0.499887
2022-01-21 -0.277661  1.479432
2022-01-22  0.396932 -0.186641
2022-01-23  0.856612  1.077370
2022-01-24 -1.342926 -0.042383
2022-01-25  0.467133  0.080259

In [45]:
# Showing label slicing, both endpoints are included:
df.loc["2022-01-21":"2022-01-23",["A","B"]]

                   A         B
2022-01-21 -0.277661  1.479432
2022-01-22  0.396932 -0.186641
2022-01-23  0.856612  1.077370

In [46]:
df.loc["2022-01-21":"2022-01-23",["A"]]

                   A
2022-01-21 -0.277661
2022-01-22  0.396932
2022-01-23  0.856612

In [47]:
df.loc["2022-01-21",["A"]]

A   -0.277661
Name: 2022-01-21 00:00:00, dtype: float64

**Selection by position**

In [48]:
df.iloc[:,:]

                   A         B         C         D
2022-01-20 -0.664715  0.499887  1.752984 -0.719964
2022-01-21 -0.277661  1.479432 -0.508587 -1.293311
2022-01-22  0.396932 -0.186641 -1.430746 -0.426380
2022-01-23  0.856612  1.077370  1.035712  0.452761
2022-01-24 -1.342926 -0.042383  1.180479 -1.763657
2022-01-25  0.467133  0.080259 -0.558254 -0.557239

In [49]:
df.iloc[0:2,1:3]

                   B         C
2022-01-20  0.499887  1.752984
2022-01-21  1.479432 -0.508587

By lists of integer position locations, similar to the NumPy/Python style:

In [50]:
df

                   A         B         C         D
2022-01-20 -0.664715  0.499887  1.752984 -0.719964
2022-01-21 -0.277661  1.479432 -0.508587 -1.293311
2022-01-22  0.396932 -0.186641 -1.430746 -0.426380
2022-01-23  0.856612  1.077370  1.035712  0.452761
2022-01-24 -1.342926 -0.042383  1.180479 -1.763657
2022-01-25  0.467133  0.080259 -0.558254 -0.557239

In [51]:
df.iloc[[1,2,4],[0,3]]

                   A         D
2022-01-21 -0.277661 -1.293311
2022-01-22  0.396932 -0.426380
2022-01-24 -1.342926 -1.763657

For slicing rows explicitly:

In [52]:
df.iloc[1:3,:]

                   A         B         C         D
2022-01-21 -0.277661  1.479432 -0.508587 -1.293311
2022-01-22  0.396932 -0.186641 -1.430746 -0.426380

For slicing columns explicitly:

In [53]:
df.iloc[:,1:3]

                   B         C
2022-01-20  0.499887  1.752984
2022-01-21  1.479432 -0.508587
2022-01-22 -0.186641 -1.430746
2022-01-23  1.077370  1.035712
2022-01-24 -0.042383  1.180479
2022-01-25  0.080259 -0.558254

For getting a value explicitly:

In [54]:
df.iloc[1,1]

1.4794319493221915

Boolean indexing
Using a single column’s values to select data:

In [55]:
df[df["A"]>0]

                   A         B         C         D
2022-01-22  0.396932 -0.186641 -1.430746 -0.426380
2022-01-23  0.856612  1.077370  1.035712  0.452761
2022-01-25  0.467133  0.080259 -0.558254 -0.557239

Using the isin() method for filtering:

In [56]:
df3 = df.copy()

In [57]:
df3["E"] = ["one", "one", "two", "three", "four", "three"]

In [58]:
df3.head()

                   A         B         C         D      E
2022-01-20 -0.664715  0.499887  1.752984 -0.719964    one
2022-01-21 -0.277661  1.479432 -0.508587 -1.293311    one
2022-01-22  0.396932 -0.186641 -1.430746 -0.426380    two
2022-01-23  0.856612  1.077370  1.035712  0.452761  three
2022-01-24 -1.342926 -0.042383  1.180479 -1.763657   four

In [60]:
df3[df3['E'].isin(["two","three"])]

                   A         B         C         D      E
2022-01-22  0.396932 -0.186641 -1.430746 -0.426380    two
2022-01-23  0.856612  1.077370  1.035712  0.452761  three
2022-01-25  0.467133  0.080259 -0.558254 -0.557239  three

**Missing data**

pandas primarily uses the value np.nan to represent missing data. It is by default not included in computations.

In [61]:
df.index

DatetimeIndex(['2022-01-20', '2022-01-21', '2022-01-22', '2022-01-23',
               '2022-01-24', '2022-01-25'],
              dtype='datetime64[ns]', freq='D')